site_name: WIKIT.REAKF.RU
site_url: https://DmitriyPetrovskiy23.github.io/knowledge_base/
theme:
  name: material
nav:
  - Главная: index.md
  - Тестовая страница: shell.md
  - Тестовая папка:
    - Файл внутри папки: new_folder/test.md
